uecode_qpush:
    cache_service_id: null
    providers:
        - { name: aws, provider_service: my_service_id
    queues:
        default:
            provider: aws
            push_notifications: true
            subscribers:
                - { endpoint: http://example.com, protocol: http }
