#Example Configuration
uecode_qpush:
    cache_service: null
    logging_enabled: true
    providers:
        aws:
            key:
            secret:
            region:
        ironmq:
            token:
            project_id:
            host:
    queues:
        default:
            provider: aws #or ironmq
            options:
                push_notifications:     true
                notification_retries:   3
                message_delay:          0
                message_timeout:        30
                message_expiration:     604800
                messages_to_receive:    1
                receive_wait_time:      3
                subscribers:
                    - { endpoint: http://example1.com/qpush, protocol: http }
                    - { endpoint: http://example2.com/qpush, protocol: http }
