services:
    ### QPush Registry
    uecode_qpush.registry:
        class: Uecode\Bundle\QPushBundle\Provider\ProviderRegistry
    uecode_qpush:
        alias: uecode_qpush.registry

    ### QPush Default File Cache
    uecode_qpush.file_cache:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments: ['%kernel.cache_dir%/qpush', qpush.php]
        public: false

    ### QPush Event Listeners
    uecode_qpush.request_listener:
        class: Uecode\Bundle\QPushBundle\EventListener\RequestListener
        arguments:
            - '@event_dispatcher'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 254 }

    ### QPush Commands
    uecode_qpush.build_command:
        class: Uecode\Bundle\QPushBundle\Command\QueueBuildCommand
        tags:
             - { name: console.command }

    uecode_qpush.destroy_command:
        class: Uecode\Bundle\QPushBundle\Command\QueueDestroyCommand
        tags:
             - { name: console.command }

    uecode_qpush.publish_command:
        class: Uecode\Bundle\QPushBundle\Command\QueuePublishCommand
        tags:
             - { name: console.command }

    uecode_qpush.receive_command:
        class: Uecode\Bundle\QPushBundle\Command\QueueReceiveCommand
        tags:
             - { name: console.command }
